### ISSUE TITLE
Update FW version when building, using to be released version

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/cat-tracker-fw#11]
The application firmware version should match the GitHub release:

![screenshot-2019-08-19T090904](https://user-images.githubusercontent.com/188915/63246152-48793f80-c262-11e9-9569-9026658fdd60.png)

The version string is set here: https://github.com/bifravst/cat-tracker-fw/blob/e942e99879d3c656c34c3e4599684bdb4194231e/applications/cat_tracker/src/mqtt_codec/mqtt_codec.c#L261-L262

**Comment by coderbyheart** [comment]
@simensrostad I want that application firmware matches the [released version](https://github.com/bifravst/cat-tracker-fw/releases) (because what is `v0.4.0-690-gcf20e8f17f18`, does not seem to relate to any commit in this repo).

So how can the version string be set when the FW is compiled? This should happen ideally through an environment variable which will be used to update a constant in the source code, or I could also (over-)write a `version.c` file with the version information (where the default version is defined as `0.0.0-development`).

**Comment by simensrostad** [comment]
I added a file named version.h under src/mqtt_codec with a define DEVICE_APP_VERSION that can be written over.

**Comment by simensrostad** [comment]
If you find it more convenient to have it in src i can relocate it

**Comment by coderbyheart** [comment]
I mean, the app version is not exclusively related to MQTT codec, so why is it in that folder?

**Comment by simensrostad** [comment]
Yes, good point. I will move it to src.
