### ISSUE TITLE
Device should send `dev` before `roam`

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/cat-tracker-fw#30]
I have seen cases where the device did publish the `roam` data, but did not publish the `dev` data: 

```json
{
  "reported": {
    "nrfcloud__dfu_v1__app_v": "v1.0.0",
    "roam": {
      "v": {
        "rsrp": 0,
        "area": 195,
        "mccmnc": 26201,
        "cell": 26971149,
        "ip": "100.110.228.1"
      },
      "ts": 1422748837999
    }
  }
}
```

This should not happen, since both `dev` and `roam` belong together.
The device should first publish the `dev` data, then the `roam` data.

**Comment by simensrostad** [comment]
I beilieve this is fixed now
