### ISSUE TITLE
Turn this repo into a standalone app

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/cat-tracker-fw#40]
The way we maintain a fork of fw-nrfconnect-nrf is not really helpful for our release history.

This repo should be turned into a standalone app which depends on https://github.com/NordicPlayground/fw-nrfconnect-nrf/ instead of being a fork.

**Comment by VojislavM** [comment]
hi @coderbyheart so, at the moment best way to build is to follow the nrf Connect SDK setup guide, set the version to tag v1.1.0 and then just copy the cat_tracker form saga branch (from this repo) into the application folder?

Do you use Segger studio, VS Code or some other option for development? 
If you use some other option then Segger, can you please share somewhere the setup. Thanks

**Comment by coderbyheart** [comment]
@VojislavM I have extended the documentation on how to *currently* build this project [in the handbook](https://bifravst.gitbook.io/bifravst/v/saga/cat-tracker-firmware/compiling). You can always check out the [GitHub Actions workflow](https://github.com/bifravst/cat-tracker-fw/blob/3b3677d9cff92ded021b58a295538c38ace4db37/.github/workflows/build-and-release.yaml) as a reference, which sets up a blank Ubuntu image to compile the firmware.

**Comment by coderbyheart** [comment]
Great improvement @simensrostad!
