### ISSUE TITLE
AWS_FOTA cloud events: how to detect FOTA is in progress

### ISSUE THREAD

**Issue by comemaster** [bifravst/cat-tracker-fw#55]
Hello,

We have our device set up in such a way, that it connects to the network on a timer (once per day). During the connection, a FOTA Job (form AWS) might trigger, but the download is stopped since we disable the modem before it is able to complete.

In [cloud_event_handler](https://github.com/bifravst/cat-tracker-fw/blob/a6cb47dff5df08ee52573805dce64b8ccb87177d/applications/cat_tracker/src/main.c#L533)
you have a `CLOUD_EVT_FOTA_DONE` event defined.

would it be possible to create a `CLOUD_EVT_FOTA_START` event? 
I see in `cloud.h` that the `cloud_event_type` enum does not have any such field. In `aws_fota.h`, there is also only the `AWS_FOTA_EVT_DONE` and `AWS_FOTA_EVT_ERROR`. I guess this is not implemented anywhere.

The idea is that we would like to detect if a FOTA job is in progress and then not disable the modem, but instead wait for it to finish.

Do you have any pointers on how I might go about adding this?

**Comment by simensrostad** [comment]
Define a new event in ``aws_jobs.h`` and ``cloud.h``.
Propogate the event in  ``aws_jobs.c`` by setting the callback ``callback(AWS_FOTA_EVT_START)``.
In the  in ``aws_fota_cb_handler`` in ``bifravst_cloud`` call ``cloud_notify_event()`` passing in ``CLOUD_EVT_FOTA_START``.

You have to locate where the callback should be set in the fota library but im guessing line 316.

PS: I have not tested this.

**Comment by comemaster** [comment]
Yes! Thank you.

Using your suggestions I have made the following changes:

Added a new enum variant to `cloud_event_type` in cloud.h:
```c
enum cloud_event_type
{
    CLOUD_EVT_CONNECTED,
    CLOUD_EVT_DISCONNECTED,
    CLOUD_EVT_READY,
    CLOUD_EVT_ERROR,
    CLOUD_EVT_DATA_SENT,
    CLOUD_EVT_DATA_RECEIVED,
    CLOUD_EVT_PAIR_REQUEST,
    CLOUD_EVT_PAIR_DONE,
    CLOUD_EVT_FOTA_START,  // added this
    CLOUD_EVT_FOTA_DONE,
    CLOUD_EVT_COUNT
};
```
added a new eum variant to `aws_fota_evt_id` in aws_fota.h:
```c
enum aws_fota_evt_id
    {
        /** AWS FOTA complete and status reported to job document */
        AWS_FOTA_EVT_DONE,
        /** AWS FOTA error */
        AWS_FOTA_EVT_ERROR,
        /*AWS FOTA started */
        AWS_FOTA_EVT_START  // added this
    };
```

in aws_fota.c, added the callback [here](https://github.com/bifravst/cat-tracker-fw/blob/c000870d70ecfed80c969badd76ddc2aa649f138/subsys/net/lib/aws_fota/src/aws_fota.c#L326):

```c
...

		if ((fota_state == DOWNLOAD_FIRMWARE) &&
		   (evt->param.suback.message_id == SUBSCRIBE_JOB_ID_UPDATE)) {
			err = update_job_execution(client, job_id,
						   AWS_JOBS_IN_PROGRESS,
						   fota_state,
						   doc_version_number,
						   "");
			if (err) {
				return err;
			}
                       
                        callback(AWS_FOTA_EVT_START); // added this

			return 1;
		}

...
```

added a new case in the `aws_fota_cb_handler` function in bifravst_cloud.c [here](https://github.com/bifravst/cat-tracker-fw/blob/c000870d70ecfed80c969badd76ddc2aa649f138/subsys/net/lib/bifravst_cloud/src/bifravst_cloud.c#L192):

```c
...
    case AWS_FOTA_EVT_START:
        LOG_DBG("AWS_FOTA_EVT_START");
        cloud_evt.type = CLOUD_EVT_FOTA_START;
        cloud_notify_event(bifravst_cloud_backend, &cloud_evt,
                           config->user_data);
        break;
    }
...
```

and finaly in main.c i added a new case to `cloud_event_handler`, in which I simply set a flag.:

```c
...
    case CLOUD_EVT_FOTA_START: // added this
        printk("CLOUD_EVT_FOTA_START\n");
        fota_in_progress = true;
        break;
    case CLOUD_EVT_FOTA_DONE:
        printk("CLOUD_EVT_FOTA_DONE\n");
        cloud_disconnect(cloud_backend);
        fota_in_progress = false;
        sys_reboot(0);
        break;
...
```

This thus enables us to hold going offline if a FOTA job is in progress.

Thank you very much.

**Comment by simensrostad** [comment]
Glad it worked out. Good luck, any resolution to issue #54?
